name: Check docs

on:
  workflow_call:
    inputs:
      package-name:
        description: 'The name of the package folder to check.'
        default: ''
        required: true
        type: string
      package-basepath:
        description: 'The base path of the package to check, relative to the repo root.'
        default: ''
        required: true
        type: string
      check-docs:
        description: 'Whether to check documentation generation.'
        default: 'true'
        type: string

permissions: {}

jobs:
  no_op:
    if: ${{ inputs.check-docs == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: No-Op
        run: echo "Not checking docs for ${PACKAGE_NAME} because check-docs is set to false."
        env:
          PACKAGE_NAME: ${{ inputs.package-name }}
  check_docs:
    name: Check docs for ${{ inputs.package-name }}
    if: ${{ inputs.check-docs == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # TODO: remove this when moving the repo to public
    defaults:
      run:
        # Set the working-directory for all steps in this job.
        working-directory: ${{ inputs.package-basepath }}
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: ni/python-actions/setup-python@aa64e60612cb078b0c2ada666becbd70d4817d55 # v0.7.1
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@aa64e60612cb078b0c2ada666becbd70d4817d55 # v0.7.1
      - name: Check for lock changes
        run: poetry check --lock
      - name: Cache virtualenv (with docs)
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ inputs.package-basepath }}/.venv
          key: ${{ inputs.package-name }}-with-docs-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles(format('{0}/poetry.lock', inputs.package-basepath)) }}
      - name: Install ${{ inputs.package-name }} (with docs)
        run: poetry install -v --only main,docs
      - name: Generate docs
        run:  poetry run sphinx-build docs docs/_build -b html -W
      # TODO: remove uploading this artifact once publishing to RTD is setup
      - name: Upload docs artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ inputs.package-name }}-docs
          path: ${{ inputs.package-basepath }}/docs/_build/
